language: python
os: linux
env:
  global:
  - CIBW_SKIP=cp34-*
  - CIBW_BUILD=cp3?-*
  - CIBW_MANYLINUX_X86_64_IMAGE=manylinux1
  - CIBW_MANYLINUX_I686_IMAGE=manylinux1
jobs:
  include:
  - services: docker
  - os: osx
    osx_image: xcode11.2 # Python 3.8.? running on macOS 10.14
    language: shell
    before_install:
      - python3 --version
      - python3 -m pip install -U pip
      - python3 -m pip install -r requirements.txt
      - python3 -m pip install cibuildwheel==1.3.0
  - os: windows
    language: shell
    before_install:
      - choco install python --version 3.8.0
      - export PATH="/c/Python38:/c/Python/Scripts:$PATH"
install:
  - python3 setup.py develop
branches:
  only:
    - development_py3
script:
  - python3 -m pip list
  - hs -v
  - hs run -h
  - hs setup -h
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
