language: python
os: linux
env:
  global:
  - CIBW_SKIP=cp34-*
  - CIBW_BUILD=cp3?-*
  - CIBW_MANYLINUX_X86_64_IMAGE=manylinux1
  - CIBW_MANYLINUX_I686_IMAGE=manylinux1
jobs:
  include:
  - services: docker
  - os: osx
    osx_image: xcode11.2
    language: shell
  - os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.0
    - export PATH="/c/Python38:/c/Python/Scripts:$PATH"
install:
  - python -m pip install -U pip
  - python -m pip install -r requirements.txt
  - python -m pip install cibuildwheel==1.3.0
branches:
  only:
    - development_py3
script:
  - python --version
  - python setup.py develop
  - pip3 list
  - hs -v
  - hs run -h
  - hs setup -h
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
