"""
This keeps various model variables and dictionary key names, 
acceptable value ranges, and data types. These are mostly used
during setup.
"""

# dype is a dictionary holding the data type for every input. Includes 
# model variable names and input file names. Note the datetime inputs
# are identified as strings here "date" but are converted to integers
# after import. And not to be confusing but the variables identified as 
# bool type here are str in the input files and converted to bool
# upon import.

dtype = {
    "usertxt": str,
    "name": str,
    "inputdir": str,
    "outputdir": str,
    "length": float,
    "outputkm": str,
    "datastart": "date",
    "modelstart": "date",
    "modelend": "date",
    "dataend": "date",
    "flushdays": int,
    "offset": int,
    "dt": float,
    "dx": int,
    "longsample": int,
    "bcfile": str,
    "tribsites": int,
    "tribfiles": str,
    "tribkm": str,
    "accretionfile": str,
    "metsites": int,
    "metfiles": str,
    "metkm": str,
    "metheights": str,
    "calcevap": bool,
    "evapmethod": str,
    "wind_a": float,
    "wind_b": float,
    "calcalluvium": bool,
    "alluviumtemp": float,
    "morphfile": str,
    "lcdatafile": str,
    "lccodefile": str,
    "trans_count": int,
    "transsample_count": int,
    "transsample_distance": float,
    "emergent": bool,
    "lcdatainput": str,
    "canopy_data": str,
    "lcsampmethod": str,
    "heatsource8": bool,
    "penman": bool,
    "nodeID": int,
    "streamID": str,
    "km": float,
    "longitude": float,
    "latitude": float,
    "topo": float,
    "lc_code": str,
    "lc_height": float,
    "lc_canopy": float,
    "lc_lai": float,
    "lc_k": float,
    "lc_oh": float,
    "elevation": float,
    "S": float,
    "W_b": float,
    "z": float,
    "n": float,
    "Ksed": float,
    "Alpha_sed": float,
    "Dsed": float,
    "Q_hyp_frac": float,
    "phi": float,
    "Q_cont": float,
    "d_cont": float,
    "Q_accr": float,
    "T_accr": float,
    "Q_with": float,
    "cloud": float,
    "wind": float,
    "humidity": float,
    "T_air": float,
    "STREAM_ID": str,
    "NODE_ID": int,
    "STREAM_KM": float,
    "INFLOW": float,
    "TEMPERATURE": float,
    "OUTFLOW": float,
    "DATETIME": "datetime",
    "CLOUDINESS": float,
    "WIND_SPEED": float,
    "RELATIVE_HUMIDITY": float,
    "AIR_TEMPERATURE": float,
    "FLOW": float,
    "NAME": str,
    "CODE": str,
    "HEIGHT": float,
    "CANOPY": float,
    "OVERHANG": float,
    "CANOPY_DEPTH": float,
    "LONGITUDE": float,
    "LATITUDE": float,
    "TOPO_W": float,
    "TOPO_S": float,
    "TOPO_E": float,
    "LC": str,
    "HT": float,
    "ELE": float,
    "CAN": float,
    "LAI": float,
    "k": float,
    "OH": float,
    "CD": float,
    "ELEVATION": float,
    "GRADIENT": float,
    "BOTTOM_WIDTH": float,
    "CHANNEL_ANGLE_Z": float,
    "MANNINGS_n": float,
    "SED_THERMAL_CONDUCTIVITY": float,
    "SED_THERMAL_DIFFUSIVITY": float,
    "SED_HYPORHEIC_THICKNESS": float,
    "HYPORHEIC_PERCENT": float,
    "POROSITY": float,
    "COLID": int,
    "MET_NAME": str,
    "TRIB_NAME": str,
    "FILE_NAME": str,
    "MET_HEIGHT": float,
}

# drange is a dictionary holding min and max values for each input. 
# This is used by in the InputSetup class by to look for potential errors 
# with the input data.
drange = {
    "STREAM_KM": (0, 999999),
    "INFLOW": (-3000, 3000),
    "TEMPERATURE": (0, 100),
    "OUTFLOW": (-3000, 3000),
    "CLOUDINESS": (0, 1),
    "WIND_SPEED": (0, 120),
    "RELATIVE_HUMIDITY": (0, 1),
    "AIR_TEMPERATURE": (-90, 60),
    "FLOW": (-3000, 3000),
    "HEIGHT": (0, 2000),
    "CANOPY": (0, 1),
    "LAI": (0, 30),
    "k": (0, 1),
    "OVERHANG": (0, 100),
    "CANOPY_DEPTH": (0, 120),
    "LONGITUDE": (-180, 180),
    "LATITUDE": (-90, 90),
    "TOPO_W": (0, 90),
    "TOPO_S": (0, 90),
    "TOPO_E": (0, 90),
    "HT": (0, 2000),
    "ELE": (-450, 9000),
    "CAN": (0, 1),
    "OH": (0, 100),
    "CD": (0, 120),
    "ELEVATION": (-450, 9000),
    "GRADIENT": (0, 1),
    "BOTTOM_WIDTH": (0, 20000),
    "CHANNEL_ANGLE_Z": (0, 90),
    "MANNINGS_n": (0, 2),
    "SED_THERMAL_CONDUCTIVITY": (0, 40),
    "SED_THERMAL_DIFFUSIVITY": (0, 0.3),
    "SED_HYPORHEIC_THICKNESS": (0, 20),
    "HYPORHEIC_PERCENT": (0, 1),
    "POROSITY": (0, 1),
    "MET_HEIGHT": (0, 200),
}

control_keys = (
    "usertxt",
    "name",
    "inputdir",
    "outputdir",
    "length",
    "outputkm",
    "datastart",
    "modelstart",
    "modelend",
    "dataend",
    "flushdays",
    "offset",
    "dt",
    "dx",
    "longsample",
    "bcfile",
    "tribsites",
    "tribfiles",
    "tribkm",
    "accretionfile",
    "metsites",
    "metfiles",
    "metkm",
    "metheights",
    "calcevap",
    "evapmethod",
    "wind_a",
    "wind_b",
    "calcalluvium",
    "alluviumtemp",
    "morphfile",
    "lcdatafile",
    "lccodefile",
    "trans_count",
    "transsample_count",
    "transsample_distance",
    "emergent",
    "lcdatainput",
    "canopy_data",
    "lcsampmethod",
    "heatsource8",
)

legacy_cf_format_keys = {
    "metfiles": "metfiles",
    "metkm": "metkm",
    "inflowinfiles": "tribfiles",
    "inflowkm": "tribkm",
}

renamed_cf_keys = {
    "inflowsites": "tribsites",
}

# head2var is a dictionary crosswalking input headers to model 
# variable names. This is more of a temporary fix because the model 
# variable names and input headers should probably be the same.
head2var = {
    "STREAM_ID": "streamID",
    "NODE_ID": "nodeID",
    "STREAM_KM": "km",
    "LONGITUDE": "longitude",
    "LATITUDE": "latitude",
    "INFLOW": "Q_accr",
    "FLOW": "Q_accr",
    "TEMPERATURE": "T_accr",
    "OUTFLOW": "Q_with",
    "ELEVATION": "elevation",
    "GRADIENT": "S",
    "BOTTOM_WIDTH": "W_b",
    "CHANNEL_ANGLE_Z": "z",
    "MANNINGS_n": "n",
    "SED_THERMAL_CONDUCTIVITY": "Ksed",
    "SED_THERMAL_DIFFUSIVITY": "Alpha_sed",
    "SED_HYPORHEIC_THICKNESS": "Dsed",
    "HYPORHEIC_PERCENT": "Q_hyp_frac",
    "POROSITY": "phi",
    "Q_cont": "Q_cont",
    "d_cont": "d_cont",
}

# name of excel sheets
sheetnames = {
    "controlfile": "Control Settings",
    "bcfile": "Boundary Conditions",
    "accretionfile": "Accretion Flow",
    "morphfile": "Morphology Data",
    "lcdatafile": "Land Cover Data",
    "lccodefile": "Land Cover Codes",
    "metsitesfile": "Meteorological Sites",
    "tribsitesfile": "Tributary Sites",
    "metfiles": "Meteorological Data",
    "tribfiles": "Tributary Data",
}
