name: Build Mac
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        architecture: [x64]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip install --upgrade Cython==0.29.24
          pip list
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: dist-mac
          path: dist
